CREATE TABLE employees (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    document_type VARCHAR2(30 CHAR) NOT NULL,
    document_number VARCHAR2(30 CHAR) NOT NULL,
    first_name VARCHAR2(100 CHAR) NOT NULL,
    last_name VARCHAR2(100 CHAR) NOT NULL,
    email VARCHAR2(150 CHAR) NOT NULL,
    phone VARCHAR2(30 CHAR),
    job_title VARCHAR2(120 CHAR),
    department VARCHAR2(120 CHAR),
    status VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    hire_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_employees_document_number UNIQUE (document_number),
    CONSTRAINT uk_employees_email UNIQUE (email),
    CONSTRAINT ck_employees_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
